"""init

Revision ID: 432924df6761
Revises: 5a67f10f9f80
Create Date: 2026-02-06 21:29:26.516862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432924df6761'
down_revision = '5a67f10f9f80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
