"""init

Revision ID: 5a67f10f9f80
Revises: c2c7f6487c3e
Create Date: 2026-02-06 21:25:54.356408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a67f10f9f80'
down_revision = 'c2c7f6487c3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
