"""init

Revision ID: c2c7f6487c3e
Revises: 
Create Date: 2026-02-06 21:25:23.926157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c7f6487c3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('pincode', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('facilities', sa.JSON(), nullable=False),
    sa.Column('operating_hours', sa.JSON(), nullable=False),
    sa.Column('emergency_services', sa.Boolean(), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index(op.f('ix_hospitals_created_at'), 'hospitals', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('RESPIRATORY', 'CARDIAC', 'NEUROLOGICAL', 'GASTROINTESTINAL', 'DERMATOLOGICAL', 'MUSCULOSKELETAL', 'GENERAL', name='symptom_category'), nullable=False),
    sa.Column('severity_level', sa.Integer(), nullable=False),
    sa.Column('common_causes', sa.JSON(), nullable=False),
    sa.Column('related_symptoms', sa.JSON(), nullable=False),
    sa.Column('recommended_specializations', sa.JSON(), nullable=False),
    sa.Column('urgency_indicators', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptoms_category'), 'symptoms', ['category'], unique=False)
    op.create_index(op.f('ix_symptoms_created_at'), 'symptoms', ['created_at'], unique=False)
    op.create_index(op.f('ix_symptoms_name'), 'symptoms', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'DOCTOR', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('specialization', sa.JSON(), nullable=False),
    sa.Column('sub_specializations', sa.JSON(), nullable=False),
    sa.Column('license_number', sa.String(length=120), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('available_slots', sa.JSON(), nullable=False),
    sa.Column('languages_spoken', sa.JSON(), nullable=False),
    sa.Column('conditions_treated', sa.JSON(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_created_at'), 'doctors', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_doctors_license_number'), 'doctors', ['license_number'], unique=True)
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact', sa.String(length=120), nullable=True),
    sa.Column('medical_history', sa.JSON(), nullable=False),
    sa.Column('chronic_conditions', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_created_at'), 'profiles', ['created_at'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('symptom_checker_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_history', sa.JSON(), nullable=False),
    sa.Column('detected_symptoms', sa.JSON(), nullable=False),
    sa.Column('ai_suggestions', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ONGOING', 'COMPLETED', 'REFERRED', name='session_status'), nullable=False),
    sa.Column('prescription_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symptom_checker_sessions_created_at'), 'symptom_checker_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_symptom_checker_sessions_status'), 'symptom_checker_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_symptom_checker_sessions_user_id'), 'symptom_checker_sessions', ['user_id'], unique=False)
    op.create_table('doctor_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symptom_checker_session_id', sa.String(length=36), nullable=True),
    sa.Column('prescription_ids', sa.JSON(), nullable=False),
    sa.Column('recommended_doctors', sa.JSON(), nullable=False),
    sa.Column('recommendation_criteria', sa.JSON(), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['symptom_checker_session_id'], ['symptom_checker_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_recommendations_created_at'), 'doctor_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctor_recommendations_symptom_checker_session_id'), 'doctor_recommendations', ['symptom_checker_session_id'], unique=False)
    op.create_index(op.f('ix_doctor_recommendations_user_id'), 'doctor_recommendations', ['user_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=False),
    sa.Column('ai_analysis', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_doctor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_created_at'), 'prescriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_is_verified'), 'prescriptions', ['is_verified'], unique=False)
    op.create_index(op.f('ix_prescriptions_upload_date'), 'prescriptions', ['upload_date'], unique=False)
    op.create_index(op.f('ix_prescriptions_user_id'), 'prescriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_verified_by_doctor_id'), 'prescriptions', ['verified_by_doctor_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('booking_type', sa.Enum('ONLINE', 'IN_PERSON', name='booking_type'), nullable=False),
    sa.Column('symptoms_summary', sa.Text(), nullable=True),
    sa.Column('prescription_ids', sa.JSON(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='booking_rating_check'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['doctor_recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_type'), 'bookings', ['booking_type'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_doctor_id'), 'bookings', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_bookings_hospital_id'), 'bookings', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_bookings_recommendation_id'), 'bookings', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('diagnostics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('symptom_checker_session_id', sa.String(length=36), nullable=True),
    sa.Column('prescription_id', sa.String(length=36), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('prescription_text', sa.Text(), nullable=True),
    sa.Column('lab_tests', sa.JSON(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symptom_checker_session_id'], ['symptom_checker_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostics_created_at'), 'diagnostics', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnostics_doctor_id'), 'diagnostics', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_diagnostics_prescription_id'), 'diagnostics', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_diagnostics_symptom_checker_session_id'), 'diagnostics', ['symptom_checker_session_id'], unique=False)
    op.create_index(op.f('ix_diagnostics_user_id'), 'diagnostics', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'WALLET', name='payment_method'), nullable=False),
    sa.Column('transaction_id', sa.String(length=120), nullable=True),
    sa.Column('payment_gateway', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=True)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_paid_at'), 'payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_paid_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_diagnostics_user_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_symptom_checker_session_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_prescription_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_doctor_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_created_at'), table_name='diagnostics')
    op.drop_table('diagnostics')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_recommendation_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hospital_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_doctor_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_type'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_prescriptions_verified_by_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_user_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_upload_date'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_is_verified'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_at'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_doctor_recommendations_user_id'), table_name='doctor_recommendations')
    op.drop_index(op.f('ix_doctor_recommendations_symptom_checker_session_id'), table_name='doctor_recommendations')
    op.drop_index(op.f('ix_doctor_recommendations_created_at'), table_name='doctor_recommendations')
    op.drop_table('doctor_recommendations')
    op.drop_index(op.f('ix_symptom_checker_sessions_user_id'), table_name='symptom_checker_sessions')
    op.drop_index(op.f('ix_symptom_checker_sessions_status'), table_name='symptom_checker_sessions')
    op.drop_index(op.f('ix_symptom_checker_sessions_created_at'), table_name='symptom_checker_sessions')
    op.drop_table('symptom_checker_sessions')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_created_at'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_license_number'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_created_at'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symptoms_name'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_created_at'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_category'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_created_at'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
