"""add_symptom_progression_column

Revision ID: fd8415973e9e
Revises: 432924df6761
Create Date: 2026-03-12 15:08:25.668580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8415973e9e'
down_revision = '432924df6761'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symptom_checker_sessions', sa.Column('symptom_progression', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symptom_checker_sessions', 'symptom_progression')
    # ### end Alembic commands ###
